{
 "title": "Database CPU Activity",
 "description": "NDB CPU monitoring dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "LDM CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\",threadName=\"ldm\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=\"ldm\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=\"ldm\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\",threadName=\"ldm\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "recv CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\",threadName=~\"recv|recv_main_rep|recv_tc|recv_ldm_tc|recv_ldm_tc_main|recv_ldm_tc_rep|recv_ldm_tc_main_rep\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=~\"recv|recv_main_rep|recv_tc|recv_ldm_tc|recv_ldm_tc_main|recv_ldm_tc_rep|recv_ldm_tc_main_rep\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=~\"recv|recv_main_rep|recv_tc|recv_ldm_tc|recv_ldm_tc_main|recv_ldm_tc_rep|recv_ldm_tc_main_rep\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\",threadName=~\"recv|recv_main_rep|recv_tc|recv_ldm_tc|recv_ldm_tc_main|recv_ldm_tc_rep|recv_ldm_tc_main_rep\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "TC CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\",threadName=\"tc\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=\"tc\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=\"tc\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\",threadName=\"tc\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "rep CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\",threadName=\"rep\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=\"rep\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=\"rep\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\",threadName=\"rep\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "main CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_exec_percentage{nodeID=\"$nodeID\",threadName=~\"main|main_rep\"})",
     "legendFormat": "{{ threadName }} Execute"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=~\"main|main_rep\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=~\"main|main_rep\"})",
     "legendFormat": "{{ threadName }} Send"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_spin_percentage{nodeID=\"$nodeID\",threadName=~\"main|main_rep\"})",
     "legendFormat": "{{ threadName }} Spin"
    }
   ]
  },
  {
   "title": "send CPU stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_sleep_percentage{nodeID=\"$nodeID\",threadName=\"send\"})",
     "legendFormat": "{{ threadName }} Sleep"
    },
    {
     "expr": "sum by (threadName)(ndb_ndbinfo_send_percentage{nodeID=\"$nodeID\",threadName=\"send\"})",
     "legendFormat": "{{ threadName }} Send"
    }
   ]
  }
 ]
}