{
 "title": "RDRS1 Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rdrs_instance",
    "label": "rdrs_instance",
    "query": {
     "query": "label_values(rdrs_rondb_connection_state, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RonDB and REST Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rdrs_rondb_connection_state{instance=\"$rdrs_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of NDB Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "rdrs_rondb_total_ndb_objects{instance=\"$rdrs_instance\"}",
     "legendFormat": "NDB Objects - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rdrs_go_runtime_number_of_go_routines{instance=\"$rdrs_instance\"}",
     "legendFormat": "Num Go Routines - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rdrs_http_connection_count{instance=\"$rdrs_instance\"}",
     "legendFormat": "HTTP Client Connections - {{instance}}"
    },
    {
     "expr": "rdrs_grpc_connection_count{instance=\"$rdrs_instance\"}",
     "legendFormat": "GRPC Client Connections - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rdrs_go_runtime_allocated_memory{instance=\"$rdrs_instance\"}",
     "legendFormat": "Memory Allocated - {{instance}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "rdrs_instance" },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(rdrs_endpoints_response_time_summary_count{endpoint!=\"Metrics\"}[1m])",
     "legendFormat": "{{endpoint}} - {{method}}"
    },
    {
     "expr": "sum by() (rate(rdrs_endpoints_response_time_summary_count{endpoint!=\"Metrics\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Response Time Percentile In Microseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rdrs_endpoints_response_time_summary{quantile=\"0.99\", endpoint!=\"Metrics\"} / 1000",
     "legendFormat": "{{endpoint}} -{{method}} - {{instance}} - {{quantile}}%"
    }
   ]
  },
  {
   "title": "Response Status Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status, api_type) (rate(rdrs_endpoints_response_status_count{endpoint!=\"Metrics\"}[1m])) / on() group_left() (sum(rate(rdrs_endpoints_response_status_count{endpoint!=\"Metrics\"}[1m]) + 0.0001)  * 1.0) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(endpoint,api_type) (rate(rdrs_endpoints_response_status_count{endpoint!=\"Metrics\", status!=\"0\", status!=\"200\"}[1m])) / on() group_left() (sum(rate(rdrs_endpoints_response_status_count{endpoint!=\"Metrics\"}[1m]) + 0.0001)  * 1.0) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Server Error HTTP 5XX , GRPC 13 Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(endpoint, api_type) (rate(rdrs_endpoints_response_status_count{endpoint!=\"Metrics\", status=~\"5..|13\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}