{
 "title": "RDRS2 Overview",
 "description": "RDRS2 overview dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "latencyMetrics",
    "label": "Latency Metrics",
    "query": "1%,5%,20%,50%,Avg,80%,95%,99%,99.9%,99.99%,100%"
   },
   {
    "name": "instance",
    "label": "Servers",
    "query": {
     "query": "label_values(rdrs_endpoints_response_status_count,instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(rdrs_endpoints_response_status_count{api_type=\"REST\"},endpoint)"
    }
   },
   { "name": "w", "label": "Window", "query": "30s,1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "RonDB req / s",
   "type": "stat",
   "description": "The rate of RonDB key lookups performed by REST servers (in order to respond to REST requests)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rdrs_endpoints_response_status_count{instance=~\"${instance:regex}\",api_type=\"NDB\",endpoint=\"key\",caused_by_endpoint=~\"${endpoint:regex}\"}[$w]))"
    }
   ]
  },
  {
   "title": "REST req / s",
   "type": "stat",
   "description": "The rate of requests received by REST servers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rdrs_endpoints_response_status_count{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w]))"
    }
   ]
  },
  {
   "title": "50% REST Latency",
   "type": "stat",
   "description": "The median response time for requests received by REST servers",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    }
   ]
  },
  {
   "title": "Avg REST Latency",
   "type": "stat",
   "description": "The average response time for requests received by REST servers",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])) / sum(rate(http_request_duration_seconds_count{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w]))"
    }
   ]
  },
  {
   "title": "99% REST Latency",
   "type": "stat",
   "description": "The 99th percentile response time for requests received by REST servers",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    }
   ]
  },
  {
   "title": "REST Latency",
   "type": "timeseries",
   "description": "Response time metrics over time for requests received by REST servers. Use the \"Latency Metrics\" dropdown at the top of the dashboard to select more metrics.",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "100%",
     "expr": "histogram_quantile(1,      sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "99.99%",
     "expr": "histogram_quantile(0.9999, sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "99.9%",
     "expr": "histogram_quantile(0.999,  sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "99%",
     "expr": "histogram_quantile(0.99,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "95%",
     "expr": "histogram_quantile(0.95,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "80%",
     "expr": "histogram_quantile(0.80,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "Avg",
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])) / sum(rate(http_request_duration_seconds_count{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w]))"
    },
    {
     "legendFormat": "50%",
     "expr": "histogram_quantile(0.50,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "20%",
     "expr": "histogram_quantile(0.20,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "5%",
     "expr": "histogram_quantile(0.05,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    },
    {
     "legendFormat": "1%",
     "expr": "histogram_quantile(0.01,   sum by (le) (rate(http_request_duration_seconds_bucket{instance=~\"${instance:regex}\",endpoint=~\"${endpoint:regex}\"}[$w])))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "The number of nodes (VMs, containers, or machines) in the cluster",
   "gridPos": { "h": 16, "w": 2, "x": 20, "y": 4 },
   "targets": [
    {
     "legendFormat": "Data nodes",
     "expr": "count (count by (instance) (node_cpu_seconds_total{instance_type=\"ndbmtd\"}))"
    },
    {
     "legendFormat": "MySQL Servers",
     "expr": "count (count by (instance) (node_cpu_seconds_total{instance_type=\"mysqld\"}))"
    },
    {
     "legendFormat": "REST Servers",
     "expr": "count (count by (instance) (node_cpu_seconds_total{instance_type=\"rdrs\"  }))"
    },
    {
     "legendFormat": "Bench nodes",
     "expr": "count (count by (instance) (node_cpu_seconds_total{instance_type=\"bench\" }))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "For each node in the cluster, the average CPU use (all non-idle time) is measured. For each node type, the maximum of those averages is displayed here. For data nodes, the information comes from RonSQL internals, and for the other types OS info is used.",
   "gridPos": { "h": 16, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "legendFormat": "Data nodes",
     "expr": "max(avg by (nodeID) (1-(ndb_ndbinfo_spin_percentage+ndb_ndbinfo_sleep_percentage)/100))"
    },
    {
     "legendFormat": "MySQL Servers",
     "expr": "max(avg by (instance) ((sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"mysqld\",mode!=\"idle\"}[$w]))) / (sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"mysqld\"}[$w])))))"
    },
    {
     "legendFormat": "REST Servers",
     "expr": "max(avg by (instance) ((sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"rdrs\",mode!=\"idle\"}[$w]))) / (sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"rdrs\"}[$w])))))"
    },
    {
     "legendFormat": "Bench nodes",
     "expr": "max(avg by (instance) ((sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"bench\",mode!=\"idle\"}[$w]))) / (sum by (instance, cpu) (rate(node_cpu_seconds_total{instance_type=\"bench\"}[$w])))))"
    }
   ]
  }
 ]
}